tut:
  outputs:
    dev:
      account: du86785.eu-west-2
      database: scratch
      password: Nurmak01__
      role: accountadmin
      schema: workspace
      threads: 1
      type: snowflake
      user: azaman
      warehouse: xsmall
  target: dev
