version: 2
models:

  - name: tab_materialisation_not_null_test
    description: model to test not null and unique 
    columns:
       - name: id
         description: primary key
         tests:
            - unique
            - not_null

